# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
#   'bundle exec jekyll serve'.
# If you change this file, please restart the server process.

# -------------------------------------
# Site Settings
# -------------------------------------
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title  }}, {{ site.email  }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable  }}.

name: Gianluca Nitti
title: GSoC Devlog
description: Tracking progress on "Server API" Google Summer of Code project with MovingBlocks

gh_name: gianluca-nitti
gh_commits: https://www.github.com/gianluca-nitti/FacadeServer/commits/?author=gianluca-nitti
gh_prs: https://github.com/MovingBlocks/FacadeServer/pulls?utf8=%E2%9C%93&q=is:pr+author:gianluca-nitti
gh_issues: https://github.com/MovingBlocks/FacadeServer/issues?utf8=%E2%9C%93&q=is:issue+author:gianluca-nitti
gh_project: https://www.github.com/gianluca-nitti/FacadeServer

# -------------------------------------
# Build Settings
# -------------------------------------
markdown: kramdown
future: true
encodig: utf-8
highlighter: rouge
baseurl: /GSoC-2017-devlog
